version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: conecta_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conecta_toolv1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: [
      "postgres", 
      "-c", "shared_preload_libraries=pg_cron",
      "-c", "cron.database_name=conecta_toolv1"
    ]

volumes:
  postgres_data:
