FROM postgres:14

# Instalar dependencias necesarias
RUN apt-get update \
    && apt-get install -y git make gcc postgresql-server-dev-14 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Clonar e instalar pg_cron desde el código fuente
RUN git clone https://github.com/citusdata/pg_cron.git \
    && cd pg_cron \
    && make \
    && make install
